- name: Check if Appliance is up and running
  wait_for:
    host: "{{ inventory_hostname }}"
    port: "{{ lmi_port }}"
    timeout: 10
    state: started
  check_mode: no
  when: start_config_executed_once is not defined

- name: Check if there are pending changes on the appliance
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     False
    action: ibmsecurity.isam.appliance.commit
  check_mode: yes
  when: start_config_executed_once is not defined
  register: ret_obj

- name: If Appliance has pending changes - then fail
  fail:
    msg: This appliance has pending changes, please commit or rollback before re-running.
  when: ret_obj.changed

- name: Snapshot Appliance as Backup
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.base.snapshots.create
    isamapi:
      comment: "{{ start_config_comment }}"
  when: start_config_executed_once is not defined

- name: Set flag to avoid multiple executions
  set_fact:
    start_config_executed_once: True