# check whether ISAM appliance LMI is ready and accept default password
- name: check ISAM appliance
  uri:
    url: "https://{{inventory_hostname}}/lmi"
    user: admin
    password: admin
    method: GET
    return_content: yes
    force_basic_auth: yes
    status_code: 200, 403
    validate_certs: false
    HEADER_Accept: "application/json"
  when: start_config_executed_once is not defined
  register: result

# if default password fails we do not go through firststeps and change password
- set_fact:
    firststeps: true
  when: start_config_executed_once is not defined and result is defined and result.status == 200 and result.json.sla is defined

# Go through basic set up to accept license and set up FIPS only needed
- include: firststeps.yml
  dynamic: true
  when: start_config_executed_once is not defined and firststeps is defined

- name: Check if Appliance is up and running
  wait_for:
    host: "{{ inventory_hostname }}"
    port: "{{ lmi_port }}"
    timeout: 10
    state: started
  check_mode: no
  when: start_config_executed_once is not defined

- name: Check if there are pending changes on the appliance
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     False
    action: ibmsecurity.isam.appliance.commit
  check_mode: yes
  when: start_config_executed_once is not defined
  register: ret_obj

- name: If Appliance has pending changes - then fail
  fail:
    msg: This appliance has pending changes, please commit or rollback before re-running.
  when: start_config_executed_once is not defined and ret_obj.changed

- name: Snapshot Appliance as Backup
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.base.snapshots.create
    isamapi:
      comment: "{{ start_config_comment }}"
  when: start_config_executed_once is not defined

- name: Set flag to avoid multiple executions
  set_fact:
    start_config_executed_once: True
  when: start_config_executed_once is not defined
